import Navbar from "@/components/Navbar";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import "./globals.css";
import { ThemeProvider } from "next-themes";

export const metadata = {
  title: "FlipZon",
  description: "Generated by create next app and shadcnui",
};


import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class">
            <Navbar />
            <main className="container mx-auto px-4 pt-16">
              {children}
            </main>
          </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
    
  );
}
