import Navbar from "@/components/Navbar";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import "./globals.css";
import { ThemeProvider } from "next-themes";


export const metadata = {
  title: "FlipZon",
  description: "Generated by create next app and shadcnui",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
       <html lang="en">
      <body>
      <header className="flex justify-end items-center p-4 gap-4 h-16">
          </header>
        <ThemeProvider attribute="class">
          <Navbar/>
            <main className="container mx-auto px-4 pt-16">
          {children}
            </main>
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
   
  );
}


